require('plugins')
require('settings')

require('autocmd')
require('blame-line')
require('comment-toggle')
require('completion')
require('git')
require('indent-guide-lines')
require('lint')
require('lsp')
require('maps')
require('md-img-paste')
require('md-preview')
require('projects')
require('refactor')
require('statusline')
require('tree-file-explorer')
require('treesitter')
require('whichkey')
require('saga')
require('symbols')
require('snippet')
require('whitespace')

require('colors')
