local p = require("code-agents.prompts")
local core = require("code-agents.core")

describe("prompts.search", function()
  it("instructs the exact format the parser consumes, round-trips", function()
    local prompt = p.search("where is the parser?")
    assert.is_truthy(prompt:find("where is the parser?", 1, true))
    assert.is_truthy(prompt:find("path:line:col", 1, true))
    -- contract: a line shaped as instructed must parse back to one qf item
    local parsed = core.parse_search_results("src/foo.lua:12:3: the parser\n")
    assert.are.equal(1, #parsed)
  end)

  it("nudges toward ripgrep", function()
    assert.is_truthy(p.search("q"):find("rg", 1, true))
  end)
end)

describe("prompts.ask", function()
  it("embeds the question, asks for brevity, and requires cited sources", function()
    local prompt = p.ask("how does auth work?")
    assert.is_truthy(prompt:find("how does auth work?", 1, true))
    assert.is_truthy(prompt:lower():find("brief"))
    assert.is_truthy(prompt:lower():find("cite"))
    assert.is_truthy(prompt:lower():find("source"))
  end)

  it("includes optional selection context", function()
    assert.is_truthy(p.ask("what is this?", "Context — foo.lua:1-3"):find("Context — foo.lua:1-3", 1, true))
  end)
end)

describe("prompts.command", function()
  it("includes the task and optional selection context", function()
    local prompt = p.command("add a foo function", "Context — bar.lua:1-3")
    assert.is_truthy(prompt:find("add a foo function", 1, true))
    assert.is_truthy(prompt:find("Context — bar.lua:1-3", 1, true))
  end)

  it("works with no context", function()
    assert.is_truthy(p.command("make a new module"):find("make a new module", 1, true))
  end)

  it("steers exploration toward the Read/Grep/Glob tools", function()
    local prompt = p.command("do x")
    assert.is_truthy(prompt:find("Grep", 1, true))
    assert.is_truthy(prompt:find("Read", 1, true))
  end)

  it("frames an autonomous background agent that doesn't pause to ask", function()
    assert.is_truthy(p.command("do x"):lower():find("without pausing to ask", 1, true))
  end)

  it("discourages approval-gated bash (prefer tools; keep bash to plain reads in-worktree)", function()
    local prompt = p.command("do x"):lower()
    assert.is_truthy(prompt:find("approval", 1, true))
  end)

  it("stays surgical without forbidding tests (must not conflict with TDD)", function()
    local prompt = p.command("do x"):lower()
    assert.is_truthy(prompt:find("surgical", 1, true))
    -- must NOT tell the agent to skip tests — that would contradict the TDD rule in CLAUDE.md
    assert.is_nil(prompt:find("no tests", 1, true))
    assert.is_nil(prompt:find("don't add tests", 1, true))
  end)
end)

describe("prompts.inject_focus", function()
  it("prepends the focus above the prompt when set", function()
    local out = p.inject_focus("Task: do the thing", "ship the parser refactor")
    assert.is_truthy(out:find("ship the parser refactor", 1, true))
    assert.is_truthy(out:find("Task: do the thing", 1, true))
    -- focus appears before the original prompt
    assert.is_true(out:find("ship the parser refactor", 1, true) < out:find("Task: do the thing", 1, true))
  end)

  it("is a no-op (byte-identical) when focus is nil or empty/whitespace", function()
    local prompt = p.search("find x")
    assert.are.equal(prompt, p.inject_focus(prompt, nil))
    assert.are.equal(prompt, p.inject_focus(prompt, ""))
    assert.are.equal(prompt, p.inject_focus(prompt, "   \n  "))
  end)

  it("introduces no path:line:col-shaped line the search parser would grab", function()
    local out = p.inject_focus(p.search("q"), "refactor the auth module")
    local extra = core.parse_search_results(out)
    -- the focus block adds no parseable qf items beyond what the format line already implies
    assert.are.equal(0, #extra)
  end)
end)

describe("prompts.explain", function()
  it("embeds the file:range header and the selection", function()
    local prompt = p.explain("local x = 1", "src/foo.lua", 10, 10)
    assert.is_truthy(prompt:find("src/foo.lua", 1, true))
    assert.is_truthy(prompt:find("10", 1, true))
    assert.is_truthy(prompt:find("local x = 1", 1, true))
  end)

  it("instructs brevity", function()
    assert.is_truthy(p.explain("x", "f", 1, 1):lower():find("brief"))
  end)
end)
