#!/usr/bin/env node

const http = require('http');

if (process.argv.length < 3) {
    console.error('Usage: http_listener.js <port>');
    process.exit(1);
}

const PORT = parseInt(process.argv[2], 10);

const server = http.createServer((req, res) => {
    console.log('---')
    console.log('Request received:');
    console.log(`Method: ${req.method}`);
    console.log(`URL: ${req.url}`);
    console.log(`Headers: ${JSON.stringify(req.headers)}`);

    let body = '';
    req.on('data', (chunk) => {
        body += chunk.toString();
    });

    req.on('end', () => {
        console.log(`Body: ${body}`);
        res.statusCode = 200;
        res.setHeader('Content-Type', 'text/plain');
        res.end('OK');
    });
});

server.listen(PORT, () => {
    console.log(`Listening on http://localhost:${PORT}`);
});
